### ISSUE TITLE
*.d.ts files need to be part of the src tree; NOT stored among compile output

### ISSUE THREAD

**Issue by ivanderk** [oasp/oasp4fn#1]
The *.d.ts files of the project are stored in the directory "dist" which is the directory where the generated *.js files are stored. That is a bug.  *.d.ts files *need* to be part of the src tree; *NOT* stored among compile output

For example see: https://github.com/Microsoft/TypeScript-Node-Starter/tree/master/src/types

**Comment by sjimenez77** [comment]
I disagree. It is not a bug, because it is necessary to include the declaration files *.d.ts if we want to make OASP4Fn compatible to TypeScript development as the documentation says here https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html 

We would be able to create a separated @types/oasp4fn package that include only the types, but it is not the recommendation anymore.

**Comment by ivanderk** [comment]
The document you point to does not mention that the files need to be part of the compilation output. On the contrary, it *specifically* states that you need to include it in the *types* property of the package.json

You have specifically included See: "types": "dist/index.d.ts"

That is my point: you should have somehting like   "types": "lib/index.d.ts"

Source files should NEVER mi mixed with compilter target files (output). You are mistaken, gentlemen. Please fix this.

**Comment by ivanderk** [comment]
Solved in commit commit 80227d46f59207be938  Files were moved to the src directory.  

Thanks

@Dalfons0   You cannot just close an issue without adressing it. So you either SOLVE the issue with how you solved it and in what commit it whas solved or or you declare it "DO NOT SOLVE" but with a clearly argumented reason,
